image: node:8.11.0

before_script:
  - npm i -g yarn
  - chmod 775 /usr/local/bin/yarn

stages:
  - build
  - test

build:
  stage: build
  script: yarn install

run test:
  stage: test
  script: yarn install && yarn run test && yarn run lint
