before_script:
  - apt update -qq && apt install -y -qq nodejs && apt install -y -qq npm
  - npm i -g yarn

stages:
  - build
  - test

build:
  stage: build
  script: yarn install

run test:
  stage: test
  script: yarn run test

run lint:
  stage: test
  script: yarn run lint
