image: node:8.11.0

before_script:
  - npm i -g yarn

stages:
  - build
  - test

build:
  stage: build
  script: yarn install

run test:
  stage: test
  script: yarn run test

run lint:
  stage: test
  script: yarn run lint
